# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'MMParallaxCell' do

pod "Masonry", :head
pod "SDWebImage", :head

end

target 'MMParallaxCellTests' do

end

